### ISSUE TITLE
Selecting items without a mouse click does not update the lastShiftRoot and can cause an unhandled exception if the lastShiftRoot was deleted

### ISSUE THREAD

**Issue by kennyjpowers** [ygoe/MultiSelectTreeView#35]
Steps to reproduce the exception in the Demo app:
- Select a node with a mouse click
- Right click that node and delete it
- Click the "Select some" button in the Selection section
- Shift + click on any node
- "Sequence contains no elements" exception is thrown because lastShiftRoot is still the node that was
  deleted but SelectedItems.Count is > 0

**Comment by ygoe** [comment]
Sounds reasonable, I'll look into it. This may take a while though.

**Comment by kennyjpowers** [comment]
Thank you very much for pushing a fix! Any chance you would be able to push an update to the NuGet package?

**Comment by ygoe** [comment]
Oh yes, sorry, I forgot about that. It's now uploaded and should be available in a moment.
